# Version 0.0.1
FROM ubuntu

# install minial linux and python packages
RUN apt-get update
RUN apt-get -y install curl wget vim python-dev python-pip build-essential libfreetype6-dev libpng12-dev pkg-config
RUN pip install pdbpp ipython nose numpy pandas matplotlib jinja2
