# Version 0.0.1
FROM company/base

RUN ln -s /opt/kerl/releases/R16B03/activate /etc/profile.d/kerl_erlang.sh   # useful for terminal usage
RUN echo "\n. /etc/profile.d/kerl_erlang.sh" >> /etc/bash.bashrc
