# Version 0.0.1
FROM ws/base_elixir

RUN mix archive.install --force https://github.com/phoenixframework/phoenix/releases/download/v1.0.3/phoenix_new-1.0.3.ez
# RUN mix phoenix.new /dev/host-server --app echo_server

VOLUME ["/dev/host-server"]
