-define(format(S, P),      lists:flatten(io_lib:format(S, P))).
-define(format_bin(S, P),  list_to_binary(lists:flatten(io_lib:format(S, P)))).
-define(format_atom(S, P), list_to_atom(lists:flatten(io_lib:format(S, P)))).
-define(stack_trace,       (try throw(stack_trace) catch throw:stack_trace -> erlang:get_stacktrace() end)).
